# 输出格式
snippet_start: \start${language}\n
snippet_stop: \stop${language}
snippet_name_start: /BTEX\color[darkred]{@}/ETEX
snippet_name: /BTEX\type[color=darkred]{${name}}/ETEX
snippet_id: /BTEX\reference[xi-${id}]{${id}}\inoutermargin{\darkred{${id}}}/ETEX
snippet_name_stop: "/BTEX\color[darkred]{\#}/ETEX"
snippet_tag: \n/BTEX\color[darkmagenta]{<${name}>}/ETEX
snippet_tag_reference: /BTEX\color[darkmagenta]{\ <${name}>\ }/ETEX
snippet_reference_start: "/BTEX\color[darkcyan]{\#}/ETEX"
snippet_reference: /BTEX\type[color=darkcyan]{${name}}/ETEX
snippet_reference_id: /BTEX\ <\in[xi-${id}]>/ETEX
snippet_reference_stop: "/BTEX\color[darkcyan]{@}/ETEX"
# snippet_emission: /BTEX=>\color[darkyellow]{${name}}<\in[xi-${id}]>/ETEX\n
snippet_prepending_operator: /BTEX\ \color[darkgreen]{\bf $\wedge+$}\ /ETEX
snippet_appending_operator: /BTEX\ \color[darkgreen]{\bf $+$}\ /ETEX